<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CentrosReclutamientoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $regimientos = [
            ["nombre_regimiento" => "RI-1 COLORADOS DE BOLIVIA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "REPM-1 SAAVEDRA", "cod_fuerza" => 1, "codigo_division" => 1],

            ["nombre_regimiento" => "BAT. COM. 1 VIDAURRE", "cod_fuerza" => 1, "codigo_division" => 1],

            ["nombre_regimiento" => "RECB-1 CALAMA", "cod_fuerza" => 1, "codigo_division" => 1],

            ["nombre_regimiento" => "RCM-4 INGAVI", "cod_fuerza" => 1, "codigo_division" => 4],

            ["nombre_regimiento" => "COL. MIL. G. VILLARROEL", "cod_fuerza" => 1, "codigo_division" => 1],

            ["nombre_regimiento" => "E.M.S.E.", "cod_fuerza" => 1, "codigo_division" => 1],

            ["nombre_regimiento" => "E.M.M.E. TCNL. A. PATIO", "cod_fuerza" => 1, "codigo_division" => 1],

            ["nombre_regimiento" => "BAT. PROD. ECOL. II MOSCOSO", "cod_fuerza" => 1, "codigo_division" => 2],

            ["nombre_regimiento" => "ESCONBOL.", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "R.I. SVA. 12 MANCHEGO", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "R.I. SVA. 16 JORDAN", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "REG. SAT. 1 TTE. GRAL. G. BUSCH", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RIM-8 AYACUCHO", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-36 SANTOS PARIAMO", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RCM-5 LANZA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "REAM-2 BOLIVAR", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. ING. II ROMAN", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RAAM-6 B. RIOJA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "REIM-23 M. TOLEDO", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BPM. IV SLDO. RODOLFO SILES", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RIM-30 MURILLO", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-21 ILLIMANI", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT.LOG.I HEROICAS RABONAS DEL PAC", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RA-1 CAMACHO", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. ING. VII SAJAMA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-22 MEJILLONES", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RIA-25 TOCOPILLA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-5 CAMPERO", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RC-3 AROMA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RA-3 PISAGUA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BATING. I CNL. EUSTAQUIO MENDEZ", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BATING. I CNL. EUSTAQUIO MENDEZ", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-20 PADILLA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-6 CAMPOS", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RC-1 AVAROA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RA-4 BULLAIN", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-11 BOQUERON", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. CMDO. Y SERV. IV", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-13 MONTES", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-11 BOQUERON", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RC-6 CASTRILLO", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RA-5 VERGARA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-15 JUNIN", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-17 INDEPENDENCIA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RC-2 BALLIVIAN", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. ING. VI RIOSINHO", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-29 ECHEVERRIA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-35 B. RACUA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-2 SUCRE", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RA-7 TUMUSLA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. ING. V OVANDO", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-26 MCAL. JUANA AZURDUY", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "R.I. AEROTRAN.18 VICTORIA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-26 MCAL. JUANA AZURDUY", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. CMDO. Y SERV. VII", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "GCAe-I APOSTOL SANTIAGO", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "REPPN-1 JUAN MARAZA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "REPM-3 E. ARCE", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-7 MARZANA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-10 CNL. IGNACIO WARNES", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-14 FLORIDA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BATING-III PANDO", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "REPM-2 AMEZAGA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RC-10 J. MERCADO", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RAA-8 TCNL. ART. FELIX AGUIRRE", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-31 E. RIOS", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-32 I. MURGUIA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-33 L. CABRERA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-3 PEREZ", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RC - 7 CHICHAS", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-4 LOA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "G.A.D.A. 97", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "G.A.E. 22", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "G.A.D.A. 91", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "G.A. 65", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "G.A. 66", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "G.A. 67", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "G.A. 83", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "G.A. 61", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "G.A.D.A. 92", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "G.A.D.A. 93", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "G.A.T. 63", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "G.A.D.A. 94", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "G.A. 62", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "G.A.D.A. 95", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "G.A.D.A. 96", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "BASE NAVAL PTO. VILLARROEL", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. P.M.N. N� 2 CARCAJE", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "AREA NAVAL No. 2", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "AREA NAVAL No. 3", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. P.M.N. N� 1 - CMDO. A.B.", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "BIM-I BAGUE", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "BASE NAVAL BALLIVIAN", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "BASE NAVAL SANTA ANA", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "BIM-II TOCOPILLA", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "BASE NAVAL R. D. GUTIERREZ", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "BIM-III MEJILLONES", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "BUQUE MULTIPROPOSITO", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "BASE NAVAL TITICACA", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "BIM-VI INDEPENDENCIA", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "BIM-IV ALIANZA", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "BIM-V CALAMA", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "BIM-VII C.PORVENIR", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "AREA NAVAL No. 1", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. CMDO. Y SERV. VIII", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. TRANS. III", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. CMDO. Y SERV. VIII", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. TRANS. IV", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. CMDO. Y SERV. VIII", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "III BRIG.", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-19 USTARIZ", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "C. MANTTO GUARACHI", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "COL.MIL.AV.", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "INSTITUTO TECNICO PPE.", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "C. MANTTO GUARACHI", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. CMDO. Y SERV. I", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. CMDO. Y SERV. II", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. CMDO. Y SERV. III", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. CMDO. Y SERV. V", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. CMDO. Y SERV. VI", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. CMDO. Y SERV. IX", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "RI-27 ANTOFAGASTA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. CMDO. Y SERV. X", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. CMDO. Y SERV. XI", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "CAE-1 CNL. CLAUDIO LOPEZ C.", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "E.C.E.M. MCAL. ANDRES DE STA CRUZ", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "E.A.A.T. MCAL. JOSE BALLIVIAN", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "LIC. MIL. EJTO. TTE. EDMUNDO ANDRADE", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "E.M.E.E. TGRAL. GERMAN BUSCH BECERRA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. TRANS. II", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BAT. TRANS. I", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BPE-III CNL. EDUARDO PACCIERI", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BPE-I DR. MARTIN CARDENAS", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BPE-V CNL. JULIO SANJINEZ GOITIA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BPE-IV TTE. VICTOR EDUARDO", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "C.G.M.E.", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "CGMMBA.-IV", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "CGMMB.- II", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "CGMMB.- III", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "CGMMB.- V", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "G.C.G.", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "POLITECNICO MILITAR DE AERONAUTICA", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "CUARTEL GENERAL CMDO. FUERZA AEREA", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "CAP. PUERTO MENOR GUANAY", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "SAR - FAB ILLIMANI", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "SAR - FAB COCHABAMBA", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "SAR - FAB SANTA CRUZ", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "SAR - FAB TARIJA", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "SAR - FAB COBIJA", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "SAR - FAB TRINIDAD", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "UNIDAD COLORADOS ZS", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "UNIDAD GADA62", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "DESERTORES RECLUTAM.", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "POSTERGADOS RECL.", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "U.E. HEROES DEL PACIFICO", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "AUX. NO HABILITADOS", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "BASE NAVAL VACA DIEZ", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "SAR - FAB CAPITAL", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "ECEMA", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "EMMFAB", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "EPTA", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "BASE NAVAL GUAQUI", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "ninguno", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "G.A. 64", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "UNIDAD 44", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "COL.MIL. CNL. GUALBERTO VILLARROEL", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "EMSE SGTO. MAXIMILIANO PAREDES", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "EMT EJ TCNL. JUAN ONDARZA LARA", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "EMSE SGTO. MAXIMILIANO PAREDES", "cod_fuerza" => 1, "codigo_division" => 1],
            ["nombre_regimiento" => "COL.MIL. TGRAL. GERMAN BUSCH BECERRA", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "PMA SBTTE. J. M. ARDILES M.", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "EMM SGTO MY JOSE SANTOS VARGAS", "cod_fuerza" => 2, "codigo_division" => 1],
            ["nombre_regimiento" => "ENM EDUARDO AVAROA HIDALGO", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "ESAA SG2 REYNALDO ZEBALLOS JOFFRE", "cod_fuerza" => 3, "codigo_division" => 1],
            ["nombre_regimiento" => "BPMN. Nº 3 CC. CGON. JUAN C. CALAMANI PEREZ", "cod_fuerza" => 3, "codigo_division" => 1],

        ];


        foreach ($regimientos as $regimiento) {
            DB::table('centros_reclutamientos')->insert([
                'codigo' => '001',
                'regimiento' => $regimiento['nombre_regimiento'],
                'codigo_division' => $regimiento['codigo_division'],
                'id_fuerza' => $regimiento['cod_fuerza'],
                'prioridad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
